## Generated by Displace Scheduler Editor

start /w C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\build\release\displace.exe -a C:\Users\fbas\Documents\GitHub\DISPLACE_input_testexample -f "testexample" -f2 "baseline" -s "simu0" -i 8762 -p 1 -o 1 -e 1 -v 0 --without-gnuplot -V 1 --num_threads 4 > ..\testexample-simu0.txt

start /w C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\build\release\displace.exe -a C:\Users\fbas\Documents\GitHub\DISPLACE_input_testexample -f "testexample" -f2 "baseline" -s "simu1" -i 8762 -p 1 -o 1 -e 1 -v 0 --without-gnuplot -V 1 --num_threads 4 > ..\testexample-simu1.txt

start /w C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\build\release\displace.exe -a C:\Users\fbas\Documents\GitHub\DISPLACE_input_testexample -f "testexample" -f2 "baseline" -s "simu2" -i 8762 -p 1 -o 1 -e 1 -v 0 --without-gnuplot -V 1 --num_threads 4 > ..\testexample-simu2.txt

start /w C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\build\release\displace.exe -a C:\Users\fbas\Documents\GitHub\DISPLACE_input_testexample -f "testexample" -f2 "baseline" -s "simu3" -i 8762 -p 1 -o 1 -e 1 -v 0 --without-gnuplot -V 1 --num_threads 4 > ..\testexample-simu3.txt

start /w C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\build\release\displace.exe -a C:\Users\fbas\Documents\GitHub\DISPLACE_input_testexample -f "testexample" -f2 "baseline" -s "simu4" -i 8762 -p 1 -o 1 -e 1 -v 0 --without-gnuplot -V 1 --num_threads 4 > ..\testexample-simu4.txt

start /w C:\Users\fbas\Documents\GitHub\DISPLACE_GUI\build\release\displace.exe -a C:\Users\fbas\Documents\GitHub\DISPLACE_input_testexample -f "testexample" -f2 "baseline" -s "simu5" -i 8762 -p 1 -o 1 -e 1 -v 0 --without-gnuplot -V 1 --num_threads 4 > ..\testexample-simu5.txt

PAUSE
